apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-django
  labels:
    app: django
data: 
  DB_NAME : weatherdb
  DB_USER : admin
  DB_HOST : "rds-instance.cpkfci27pmjq.us-east-1.rds.amazonaws.com"
  DB_PORT : "3306"
  AWS_REGION : us-east-1
  SNS_TOPIC_ARN : 'arn:aws:sns:us-east-1:116695809482:weather-daily-notifications'
  COGNITO_USER_POOL_ID : "us-east-1_7XFhFqcFH"
  COGNITO_APP_CLIENT_ID : "6o114vulaf3pj0opf7doo0n96n"
  COGNITO_DOMAIN : "https://weather-scanner-app.auth.us-east-1.amazoncognito.com"
  COGNITO_REDIRECT_URI : "http://34.117.38.205.nip.io/cognito/google/callback/"
  LOGOUT_REDIRECT_URI : "http://34.117.38.205.nip.io/login/"
  COGNITO_IDENTITY_PROVIDER : "Google"
