apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-django
  labels:
    app: django
data: 
  DB_NAME : weatherdb
  DB_USER : admin
  DB_HOST : "rds-instance.cpkfci27pmjq.us-east-1.rds.amazonaws.com"
  DB_PORT : "3306"
  AWS_REGION : us-east-1
  SNS_TOPIC_ARN : 'arn:aws:sns:us-east-1:116695809482:weather-daily-notifications'
  COGNITO_USER_POOL_ID : "us-east-1_yTYcSdPkJ"
  COGNITO_APP_CLIENT_ID : "2tb1gja00u0kksil8teddck9o5"
  COGNITO_DOMAIN : "https://weather-scanner-app.auth.us-east-1.amazoncognito.com"
  COGNITO_REDIRECT_URI : "https://34.128.177.59.nip.io/cognito/google/callback/"
  LOGOUT_REDIRECT_URI : "https://34.128.177.59.nip.io/login/"
  DOMAIN : "https://34.128.177.59.nip.io"
  COGNITO_IDENTITY_PROVIDER : "Google"
  MONGO_DB_URI : "mongodb://foo:mustbeeightchars@weather-scanner-nlb-ad65dd6f7883376f.elb.eu-west-1.amazonaws.com:27017/weather_scanner?tls=true&retryWrites=false&tlsInsecure=true&directConnection=true"
