apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-django
  labels:
    app: django
data: 
  DB_NAME : weatherdb
  DB_USER : utente
  # DB_HOST : 192.168.0.107
  DB_HOST : 127.0.0.1
  DB_PORT : "3306"

  AWS_REGION : us-east-1
  SNS_TOPIC_ARN : 'arn:aws:sns:us-east-1:116695809482:weather-daily-notifications'

  COGNITO_USER_POOL_ID : "us-east-1_efgqJvIlr"
  COGNITO_APP_CLIENT_ID : "4e74qql1vri350oeajtptds6p7"
  COGNITO_DOMAIN : "https://weather-scanner-app.auth.us-east-1.amazoncognito.com"
  COGNITO_REDIRECT_URI : "http://localhost:8000/cognito/google/callback/"
  LOGOUT_REDIRECT_URI : "http://localhost:8000/login/"
  COGNITO_IDENTITY_PROVIDER : "Google"