apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: antoniolauro/webapp:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: secret-volume
            mountPath: "/.aws"
            readOnly: true
        ports:
        - containerPort: 8000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        envFrom:
          - configMapRef:
              name: configmap-django
      volumes:
        - name: secret-volume
          secret:
            secretName: aws-credentials