apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: antoniolauro/webapp:latest
        ports:
        - containerPort: 8000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
        envFrom:
          - configMapRef:
              name: configmap-django