name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: TUO_PROJECT_ID  # Sostituisci con il tuo Project ID di Google Cloud
  GKE_CLUSTER: tuo-cluster      # Sostituisci con il nome del tuo cluster GKE
  GKE_ZONE: europe-west1-b      # Sostituisci con la zona del tuo cluster GKE
  DEPLOYMENT_NAME: django-app # Sostituisci con il nome del tuo deployment in GKE

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GH_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: 'weatherscanner-466411'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'weather-scanner-gke'
        location: 'europe-west12'

    # Login a Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: antoniolauro
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      run: |-
        docker build -t "antoniolauro/webapp:${{ github.sha }}" -t "antoniolauro/webapp:latest" . 
        docker push -a "antoniolauro/webapp"

    - name: Get GKE credentials
      run: |-
        kubectl config set-cluster gke_weatherscanner-466411_europe-west12_weather-scanner-gke --server=https://127.0.0.1:8443 --tls-server-name=10.0.1.2

        gcloud compute ssh --zone "europe-west12-b" "gke-bastion-host" --tunnel-through-iap --project "weatherscanner-466411" -- -fNL 8443:10.0.1.2:443

    - name: Deploy to GKE
      run: |-
        # deployment viene eliminato solo se esiste
        kubectl get deployment django &> /dev/null && kubectl get deploy/django
        kubectl apply -f ./manifests
        kubectl rollout status deployment/django